name: Build WinDri APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório atual
      - name: Checkout Repositório Principal
        uses: actions/checkout@v4

      # 2. Clona a pasta/projeto secundário (winDri-app / app) na pasta correta
      - name: Checkout Módulo do App
        uses: actions/checkout@v4
        with:
          repository: LUAN228/winDri-app # Nome do seu outro repositório forkado
          path: app # Ajuste este caminho se a pasta precisar ter outro nome no projeto

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Dar permissão de execução ao Gradle
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
          elif [ -f "./app/gradlew" ]; then
            chmod +x ./app/gradlew
          fi

      - name: Compilar APK (Debug)
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug --stacktrace
          else
            gradle assembleDebug --stacktrace
          fi

      - name: Disponibilizar o APK para Download (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: WinDri-Debug-APK
          path: '**/build/outputs/apk/debug/*.apk'
